---
title: "clustering_SL_bartobar"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{clustering_SL_bartobar}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r libraries}

library('CAGEr')
library('ggplot2'); theme_set(theme_minimal())
library('BSgenome')
library('CAGErAid')

```

# Load in data from the [polishing](./vignettes/polishing.Rmd) file

```{r load in data}

ce <- readRDS('./data/BARtoBAR.rds')

```

```{r}

# load GFF files
gff <- quickGFF('/bucket/LuscombeU/live/CharlesPlessy/CAGE/2022-11-09_Barcelona_Oik/AlignWithRNAseqPipelinePE_BAR/Bar2_p4.gm.gtf')

```

# Clustering

Separate SL containing samples

```{r}

ce_sl <- ce[, ce$SLfound] |>
  normalizeTagCount(method = "simpleTpm") |>
  annotateCTSS(gff)

```

```{r plot reverse cumulatives}

plotReverseCumulatives(ce_sl,
                       fitInRange = NULL,
                       values = "raw",
                       onePlot = TRUE)

plotReverseCumulatives(ce_sl,
                       fitInRange = NULL,
                       values = "normalized",
                       onePlot = TRUE)

```

```{r simple clustering and aggregating}

ce_sl <- quickClustersSL(ce_sl, aggregate = T, gff)

```

```{r export to bed - maybe}

cctrack_sl <- exportToTrack(ce_sl, "consensusClusters")#, qLow = 0.1, qUp = 0.9)
# Error in h(simpleError(msg, call)) : 
# error in evaluating the argument 'x' in selecting a method for function 'decode': subscript contains invalid names

cctrack_sl@trackLine@description <- "CAGE Consensus Clusters for trans splicing sites"
cctrack_sl@trackLine@name <- "sl"
# Flat AG
cctrack_sl$itemRgb <- ifelse(flagByUpstreamSequences(rowRanges(consensusClustersSE(ce_sl))$dominant_ctss, "AG"), "black", "grey")

cctrack_sl[cctrack_sl$itemRgb == "black"] |> score() |> decode() |> log10() |> hist(br=100)
cctrack_sl[cctrack_sl$itemRgb == "grey"]  |> score() |> decode() |> log10() |> hist(br=100)

# cctrack_sl <- makeBed(ce_sl, TRUE)
rtracklayer::export.bed(cctrack_sl, "clusters_sl_bartobar.bed")
```
